# Generated by Django 6.0.5 on 2026-05-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('intended_use', models.CharField(blank=True, choices=[('living', 'Extra Living Space'), ('housing', 'Affordable Housing (Off-grid)'), ('rental', 'Airbnb / Guest House'), ('yoga', 'Yoga / Meditation / Spiritual Space'), ('campsite', 'Campsite / Resort'), ('education', 'Education / Classroom'), ('therapy', 'Healing / Therapy'), ('festival', 'Festival / Cultural Event'), ('other', 'Other')], max_length=32)),
                ('subject', models.CharField(choices=[('buy', 'Buy a Qara Uy'), ('parts', 'Parts & Furniture'), ('technical', 'Technical Support'), ('general', 'General Inquiry')], default='buy', max_length=32)),
                ('preferred_contact', models.CharField(choices=[('call', 'Call'), ('text', 'Text'), ('email', 'Email')], default='email', max_length=16)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Contact inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order', '-id'],
            },
        ),
    ]
